"""Tests for deterministic release-document generation."""

from __future__ import annotations

import importlib.util
import sys
from datetime import date
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).parents[1]


@pytest.fixture(scope="module")
def release_docs():
    script = REPO_ROOT / "tools" / "sync_release_docs.py"
    spec = importlib.util.spec_from_file_location("sync_release_docs", script)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def sample_releases(release_docs):
    return (
        release_docs.Release(
            version="2.0.0",
            date=date(2026, 1, 2),
            summary_zh="主要版本",
            summary_en="Major release",
            changes_zh=("中文变更",),
            changes_en=("English change",),
        ),
        release_docs.Release(
            version="1.0.0",
            date=None,
            summary_zh="初始版本",
            summary_en="Initial release",
            changes_zh=(),
            changes_en=(),
        ),
    )


def test_canonical_release_data_is_bilingual_and_newest_first(release_docs) -> None:
    releases = release_docs.load_releases(REPO_ROOT / "releases.toml")

    assert releases[0].date is not None
    assert all(release.summary_zh and release.summary_en for release in releases)
    assert all(len(release.changes_zh) == len(release.changes_en) for release in releases)


def test_expected_release_version_must_match_latest_entry(release_docs) -> None:
    releases = release_docs.load_releases(REPO_ROOT / "releases.toml")
    latest = releases[0].version

    release_docs.validate_expected_version(releases, f"v{latest}")
    with pytest.raises(ValueError, match="does not match expected release"):
        release_docs.validate_expected_version(releases, f"{latest}.unexpected")


def test_changelog_rendering_is_deterministic_and_bilingual(release_docs, sample_releases) -> None:
    expected = """\
<!-- Generated by tools/sync_release_docs.py; edit releases.toml instead. -->
# 更新记录 / Changelog

本文件由 `releases.toml` 自动生成。This file is generated from `releases.toml`.

## 2.0.0 — 2026-01-02

### 中文

主要版本

- 中文变更

### English

Major release

- English change

## 1.0.0

### 中文

初始版本

### English

Initial release
"""

    first = release_docs.render_changelog(sample_releases)
    second = release_docs.render_changelog(sample_releases)

    assert first == second == expected


def test_site_changelog_preserves_legacy_redirect_anchor(release_docs) -> None:
    releases = release_docs.load_releases(REPO_ROOT / "releases.toml")

    rendered = release_docs.render_site_changelog(releases)

    assert '<span id="legacy"></span>' in rendered


def test_invalid_or_duplicate_release_data_is_rejected(release_docs, tmp_path) -> None:
    duplicate = tmp_path / "releases.toml"
    duplicate.write_text(
        """
[[release]]
version = "1.0.0"
date = 2026-07-25
summary_zh = "测试"
summary_en = "Test"

[[release]]
version = "1.0.0"
summary_zh = "重复"
summary_en = "Duplicate"
""".lstrip(),
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="duplicate release version"):
        release_docs.load_releases(duplicate)


def test_strict_html_replacement_rejects_missing_marker(release_docs) -> None:
    with pytest.raises(ValueError, match="expected one match"):
        release_docs._replace_once("no version here", r"version \d+", "version 1", "page.html")
