# Form implementation generated from reading ui file 'add_proxy.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_AddProxy(object):
    def setupUi(self, Dialog_AddProxy):
        Dialog_AddProxy.setObjectName("Dialog_AddProxy")
        Dialog_AddProxy.resize(381, 242)
        self.label_user = QtWidgets.QLabel(parent=Dialog_AddProxy)
        self.label_user.setGeometry(QtCore.QRect(20, 120, 51, 20))
        self.label_user.setObjectName("label_user")
        self.checkBox_proxy_auth = QtWidgets.QCheckBox(parent=Dialog_AddProxy)
        self.checkBox_proxy_auth.setGeometry(QtCore.QRect(20, 90, 191, 18))
        self.checkBox_proxy_auth.setObjectName("checkBox_proxy_auth")
        self.le_username = QtWidgets.QLineEdit(parent=Dialog_AddProxy)
        self.le_username.setEnabled(False)
        self.le_username.setGeometry(QtCore.QRect(80, 120, 113, 20))
        self.le_username.setObjectName("le_username")
        self.label_name = QtWidgets.QLabel(parent=Dialog_AddProxy)
        self.label_name.setGeometry(QtCore.QRect(20, 30, 51, 20))
        self.label_name.setObjectName("label_name")
        self.label_pass = QtWidgets.QLabel(parent=Dialog_AddProxy)
        self.label_pass.setGeometry(QtCore.QRect(20, 150, 51, 20))
        self.label_pass.setObjectName("label_pass")
        self.le_password = QtWidgets.QLineEdit(parent=Dialog_AddProxy)
        self.le_password.setEnabled(False)
        self.le_password.setGeometry(QtCore.QRect(80, 150, 113, 20))
        self.le_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_password.setObjectName("le_password")
        self.label_port = QtWidgets.QLabel(parent=Dialog_AddProxy)
        self.label_port.setGeometry(QtCore.QRect(240, 60, 31, 21))
        self.label_port.setObjectName("label_port")
        self.le_port = QtWidgets.QLineEdit(parent=Dialog_AddProxy)
        self.le_port.setGeometry(QtCore.QRect(280, 60, 41, 20))
        self.le_port.setMaxLength(5)
        self.le_port.setObjectName("le_port")
        self.le_proxy_name = QtWidgets.QLineEdit(parent=Dialog_AddProxy)
        self.le_proxy_name.setGeometry(QtCore.QRect(80, 30, 140, 20))
        self.le_proxy_name.setMaxLength(255)
        self.le_proxy_name.setObjectName("le_proxy_name")
        self.label_addr = QtWidgets.QLabel(parent=Dialog_AddProxy)
        self.label_addr.setGeometry(QtCore.QRect(20, 60, 51, 20))
        self.label_addr.setObjectName("label_addr")
        self.le_address = QtWidgets.QLineEdit(parent=Dialog_AddProxy)
        self.le_address.setGeometry(QtCore.QRect(80, 60, 140, 20))
        self.le_address.setMaxLength(255)
        self.le_address.setObjectName("le_address")
        self.comboBox_type = QtWidgets.QComboBox(parent=Dialog_AddProxy)
        self.comboBox_type.setGeometry(QtCore.QRect(280, 30, 61, 22))
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.label_type = QtWidgets.QLabel(parent=Dialog_AddProxy)
        self.label_type.setGeometry(QtCore.QRect(240, 30, 30, 21))
        self.label_type.setObjectName("label_type")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_AddProxy)
        self.buttonBox.setGeometry(QtCore.QRect(180, 200, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog_AddProxy)
        self.checkBox_proxy_auth.toggled['bool'].connect(self.le_username.setEnabled) # type: ignore
        self.checkBox_proxy_auth.toggled['bool'].connect(self.le_password.setEnabled) # type: ignore
        self.buttonBox.accepted.connect(Dialog_AddProxy.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_AddProxy.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_AddProxy)
        Dialog_AddProxy.setTabOrder(self.le_proxy_name, self.comboBox_type)
        Dialog_AddProxy.setTabOrder(self.comboBox_type, self.le_address)
        Dialog_AddProxy.setTabOrder(self.le_address, self.le_port)
        Dialog_AddProxy.setTabOrder(self.le_port, self.checkBox_proxy_auth)
        Dialog_AddProxy.setTabOrder(self.checkBox_proxy_auth, self.le_username)
        Dialog_AddProxy.setTabOrder(self.le_username, self.le_password)

    def retranslateUi(self, Dialog_AddProxy):
        _translate = QtCore.QCoreApplication.translate
        Dialog_AddProxy.setWindowTitle(_translate("Dialog_AddProxy", "Add Proxy"))
        self.label_user.setText(_translate("Dialog_AddProxy", "Username"))
        self.checkBox_proxy_auth.setText(_translate("Dialog_AddProxy", "&Authorization"))
        self.label_name.setText(_translate("Dialog_AddProxy", "Name", "lable_name"))
        self.label_pass.setText(_translate("Dialog_AddProxy", "Password"))
        self.label_port.setText(_translate("Dialog_AddProxy", "Port"))
        self.label_addr.setText(_translate("Dialog_AddProxy", "Address"))
        self.comboBox_type.setItemText(0, _translate("Dialog_AddProxy", "HTTP"))
        self.comboBox_type.setItemText(1, _translate("Dialog_AddProxy", "SOCKS4"))
        self.comboBox_type.setItemText(2, _translate("Dialog_AddProxy", "SOCKS5"))
        self.label_type.setText(_translate("Dialog_AddProxy", "Type"))
