# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pps_conf.ui'
#
# Created: Tue Mar 01 22:13:06 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog_Config(object):
    def setupUi(self, Dialog_Config):
        Dialog_Config.setObjectName(_fromUtf8("Dialog_Config"))
        Dialog_Config.resize(468, 327)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun"))
        font.setPointSize(9)
        Dialog_Config.setFont(font)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_Config)
        self.buttonBox.setGeometry(QtCore.QRect(90, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(Dialog_Config)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 441, 261))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_proxy = QtGui.QWidget()
        self.tab_proxy.setObjectName(_fromUtf8("tab_proxy"))
        self.btn_del = QtGui.QPushButton(self.tab_proxy)
        self.btn_del.setGeometry(QtCore.QRect(200, 200, 75, 23))
        self.btn_del.setObjectName(_fromUtf8("btn_del"))
        self.btn_add_proxy = QtGui.QPushButton(self.tab_proxy)
        self.btn_add_proxy.setGeometry(QtCore.QRect(20, 200, 75, 23))
        self.btn_add_proxy.setObjectName(_fromUtf8("btn_add_proxy"))
        self.tableView = QtGui.QTableView(self.tab_proxy)
        self.tableView.setGeometry(QtCore.QRect(15, 10, 401, 181))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.btn_mod = QtGui.QPushButton(self.tab_proxy)
        self.btn_mod.setGeometry(QtCore.QRect(110, 200, 75, 23))
        self.btn_mod.setObjectName(_fromUtf8("btn_mod"))
        self.btn_batch = QtGui.QPushButton(self.tab_proxy)
        self.btn_batch.setGeometry(QtCore.QRect(290, 200, 121, 23))
        self.btn_batch.setObjectName(_fromUtf8("btn_batch"))
        self.tabWidget.addTab(self.tab_proxy, _fromUtf8(""))
        self.tab_advanced = QtGui.QWidget()
        self.tab_advanced.setObjectName(_fromUtf8("tab_advanced"))
        self.label_cmd = QtGui.QLabel(self.tab_advanced)
        self.label_cmd.setGeometry(QtCore.QRect(20, 60, 81, 20))
        self.label_cmd.setObjectName(_fromUtf8("label_cmd"))
        self.comboBox_cmd = QtGui.QComboBox(self.tab_advanced)
        self.comboBox_cmd.setGeometry(QtCore.QRect(100, 60, 91, 22))
        self.comboBox_cmd.setObjectName(_fromUtf8("comboBox_cmd"))
        self.comboBox_cmd.addItem(_fromUtf8(""))
        self.comboBox_cmd.addItem(_fromUtf8(""))
        self.label_localport = QtGui.QLabel(self.tab_advanced)
        self.label_localport.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.label_localport.setObjectName(_fromUtf8("label_localport"))
        self.le_localport = QtGui.QLineEdit(self.tab_advanced)
        self.le_localport.setGeometry(QtCore.QRect(100, 100, 61, 20))
        self.le_localport.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.le_localport.setMaxLength(5)
        self.le_localport.setObjectName(_fromUtf8("le_localport"))
        self.label_debug = QtGui.QLabel(self.tab_advanced)
        self.label_debug.setGeometry(QtCore.QRect(20, 180, 71, 20))
        self.label_debug.setObjectName(_fromUtf8("label_debug"))
        self.checkBox_debug = QtGui.QCheckBox(self.tab_advanced)
        self.checkBox_debug.setGeometry(QtCore.QRect(100, 180, 251, 21))
        self.checkBox_debug.setObjectName(_fromUtf8("checkBox_debug"))
        self.label_lang = QtGui.QLabel(self.tab_advanced)
        self.label_lang.setGeometry(QtCore.QRect(20, 20, 51, 20))
        self.label_lang.setObjectName(_fromUtf8("label_lang"))
        self.comboBox_lang = QtGui.QComboBox(self.tab_advanced)
        self.comboBox_lang.setGeometry(QtCore.QRect(100, 20, 141, 22))
        self.comboBox_lang.setObjectName(_fromUtf8("comboBox_lang"))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.tab_advanced)
        self.label_2.setGeometry(QtCore.QRect(200, 60, 211, 31))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_show_welcome = QtGui.QLabel(self.tab_advanced)
        self.label_show_welcome.setGeometry(QtCore.QRect(20, 140, 71, 20))
        self.label_show_welcome.setObjectName(_fromUtf8("label_show_welcome"))
        self.checkBox_show_welcome = QtGui.QCheckBox(self.tab_advanced)
        self.checkBox_show_welcome.setGeometry(QtCore.QRect(100, 140, 251, 21))
        self.checkBox_show_welcome.setObjectName(_fromUtf8("checkBox_show_welcome"))
        self.tabWidget.addTab(self.tab_advanced, _fromUtf8(""))

        self.retranslateUi(Dialog_Config)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_Config.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_Config.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Config)
        Dialog_Config.setTabOrder(self.btn_add_proxy, self.btn_mod)
        Dialog_Config.setTabOrder(self.btn_mod, self.btn_del)
        Dialog_Config.setTabOrder(self.btn_del, self.btn_batch)
        Dialog_Config.setTabOrder(self.btn_batch, self.tableView)
        Dialog_Config.setTabOrder(self.tableView, self.comboBox_lang)
        Dialog_Config.setTabOrder(self.comboBox_lang, self.comboBox_cmd)
        Dialog_Config.setTabOrder(self.comboBox_cmd, self.le_localport)
        Dialog_Config.setTabOrder(self.le_localport, self.checkBox_show_welcome)
        Dialog_Config.setTabOrder(self.checkBox_show_welcome, self.checkBox_debug)
        Dialog_Config.setTabOrder(self.checkBox_debug, self.buttonBox)
        Dialog_Config.setTabOrder(self.buttonBox, self.tabWidget)

    def retranslateUi(self, Dialog_Config):
        Dialog_Config.setWindowTitle(QtGui.QApplication.translate("Dialog_Config", "PPS Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_del.setText(QtGui.QApplication.translate("Dialog_Config", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_proxy.setText(QtGui.QApplication.translate("Dialog_Config", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mod.setText(QtGui.QApplication.translate("Dialog_Config", "&Modify", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_batch.setText(QtGui.QApplication.translate("Dialog_Config", "&Batch Add/Mod/Del", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_proxy), QtGui.QApplication.translate("Dialog_Config", "Proxy List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cmd.setText(QtGui.QApplication.translate("Dialog_Config", "Proxy Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_cmd.setItemText(0, QtGui.QApplication.translate("Dialog_Config", "polipo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_cmd.setItemText(1, QtGui.QApplication.translate("Dialog_Config", "ip_relay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_localport.setText(QtGui.QApplication.translate("Dialog_Config", "Local Port", None, QtGui.QApplication.UnicodeUTF8))
        self.le_localport.setText(QtGui.QApplication.translate("Dialog_Config", "8888", None, QtGui.QApplication.UnicodeUTF8))
        self.label_debug.setText(QtGui.QApplication.translate("Dialog_Config", "Debug Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_debug.setText(QtGui.QApplication.translate("Dialog_Config", "Show &debug info in console", None, QtGui.QApplication.UnicodeUTF8))
        self.label_lang.setText(QtGui.QApplication.translate("Dialog_Config", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_lang.setItemText(0, QtGui.QApplication.translate("Dialog_Config", "简体中文", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_lang.setItemText(1, QtGui.QApplication.translate("Dialog_Config", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_Config", "(Don\'t change this in normal use)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_show_welcome.setText(QtGui.QApplication.translate("Dialog_Config", "Show Welcome", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_show_welcome.setText(QtGui.QApplication.translate("Dialog_Config", "Show &welcome info when program start", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advanced), QtGui.QApplication.translate("Dialog_Config", "Advanced", None, QtGui.QApplication.UnicodeUTF8))

