#!/usr/bin/env python3
"""Generate release documentation from the repository's canonical release data."""

from __future__ import annotations

import argparse
import difflib
import html
import re
import sys
import tomllib
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Final

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
DEFAULT_DATA_FILE: Final = REPO_ROOT / "releases.toml"
DEFAULT_SITE_ROOT: Final = REPO_ROOT / "htdocs"
VERSION_PATTERN: Final = r"\d+(?:\.\d+){1,3}"


@dataclass(frozen=True)
class Release:
    version: str
    date: date | None
    summary_zh: str
    summary_en: str
    changes_zh: tuple[str, ...]
    changes_en: tuple[str, ...]

    @property
    def anchor(self) -> str:
        return "v" + self.version.replace(".", "")


def _string_list(value: object, field: str, version: str) -> tuple[str, ...]:
    if value is None:
        return ()
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        raise ValueError(f"release {version}: {field} must be an array of non-empty strings")
    return tuple(value)


def load_releases(path: Path) -> tuple[Release, ...]:
    with path.open("rb") as stream:
        document = tomllib.load(stream)

    raw_releases = document.get("release")
    if not isinstance(raw_releases, list) or not raw_releases:
        raise ValueError(f"{path}: expected at least one [[release]] entry")

    releases: list[Release] = []
    seen_versions: set[str] = set()
    previous_version_key: tuple[int, ...] | None = None
    for raw in raw_releases:
        if not isinstance(raw, dict):
            raise ValueError(f"{path}: each [[release]] entry must be a table")
        version = raw.get("version")
        if not isinstance(version, str) or re.fullmatch(VERSION_PATTERN, version) is None:
            raise ValueError(f"{path}: invalid numeric release version: {version!r}")
        if version in seen_versions:
            raise ValueError(f"{path}: duplicate release version: {version}")
        seen_versions.add(version)
        version_key = tuple(int(part) for part in version.split("."))
        version_key += (0,) * (4 - len(version_key))
        if previous_version_key is not None and version_key >= previous_version_key:
            raise ValueError(f"{path}: releases must be ordered newest-first near {version}")
        previous_version_key = version_key

        release_date = raw.get("date")
        if release_date is not None and not isinstance(release_date, date):
            raise ValueError(f"release {version}: date must be an unquoted TOML local date")

        summaries: dict[str, str] = {}
        for field in ("summary_zh", "summary_en"):
            value = raw.get(field)
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"release {version}: {field} must be a non-empty string")
            summaries[field] = value.strip()

        changes_zh = _string_list(raw.get("changes_zh"), "changes_zh", version)
        changes_en = _string_list(raw.get("changes_en"), "changes_en", version)
        if len(changes_zh) != len(changes_en):
            raise ValueError(
                f"release {version}: changes_zh and changes_en must have equal lengths"
            )

        releases.append(
            Release(
                version=version,
                date=release_date,
                summary_zh=summaries["summary_zh"],
                summary_en=summaries["summary_en"],
                changes_zh=changes_zh,
                changes_en=changes_en,
            )
        )

    if releases[0].date is None:
        raise ValueError(f"latest release {releases[0].version} must have an exact date")
    return tuple(releases)


def validate_expected_version(releases: tuple[Release, ...], expected: str | None) -> None:
    if expected is None:
        return
    normalized = expected.removeprefix("v")
    if releases[0].version != normalized:
        raise ValueError(
            f"latest releases.toml version {releases[0].version} does not match "
            f"expected release {normalized}"
        )


def render_changelog(releases: tuple[Release, ...]) -> str:
    lines = [
        "<!-- Generated by tools/sync_release_docs.py; edit releases.toml instead. -->",
        "# 更新记录 / Changelog",
        "",
        "本文件由 `releases.toml` 自动生成。This file is generated from `releases.toml`.",
        "",
    ]
    for release in releases:
        suffix = f" — {release.date.isoformat()}" if release.date else ""
        lines.extend(
            [
                f"## {release.version}{suffix}",
                "",
                "### 中文",
                "",
                release.summary_zh,
                "",
            ]
        )
        lines.extend(f"- {change}" for change in release.changes_zh)
        if release.changes_zh:
            lines.append("")
        lines.extend(["### English", "", release.summary_en, ""])
        lines.extend(f"- {change}" for change in release.changes_en)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _time_html(release: Release) -> str:
    if release.date is None:
        return ""
    iso_date = release.date.isoformat()
    return f'<time datetime="{iso_date}">{iso_date}</time>'


def _changes_html(changes: tuple[str, ...]) -> str:
    if not changes:
        return ""
    return "<ul>" + "".join(f"<li>{html.escape(change)}</li>" for change in changes) + "</ul>"


def render_site_changelog(releases: tuple[Release, ...]) -> str:
    latest = releases[0]
    sections = []
    for release in releases:
        sections.append(
            f'  <section class="release" id="{release.anchor}"><h2>{release.version}</h2>'
            f"{_time_html(release)}<p>{html.escape(release.summary_zh)}</p>"
            f"{_changes_html(release.changes_zh)}</section>"
        )

    toc_releases = releases[:10]
    toc = "".join(f'<a href="#{release.anchor}">{release.version}</a>' for release in toc_releases)
    if len(releases) > len(toc_releases):
        toc += f'<a href="#{releases[len(toc_releases)].anchor}">更早版本</a>'

    return f"""<!doctype html>
<html lang="zh-CN">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="PyProxySwitch 从 {releases[-1].version} 到 {latest.version} 的版本更新记录。"><title>版本更新记录 — PyProxySwitch</title><link rel="stylesheet" href="css/style.css"></head>
<body>
<header class="site-header"><nav class="nav" aria-label="主导航"><a class="brand" href="index.html"><img src="images/PyProxySwitch-Logo.png" alt=""><span>PyProxySwitch</span></a><div class="nav-links"><a href="index.html">首页</a><a href="download.html">下载</a><a href="documentation.html">文档</a><a href="changelog.html" aria-current="page">更新记录</a><a href="screenshot.html">界面</a><a href="support.html">支持</a></div></nav><div class="hero compact"><h1>版本更新记录</h1><p>重点记录架构、兼容性与用户可见行为变化。</p></div></header>
<main class="page layout">
<article class="content">
{chr(10).join(sections)}
  <p class="muted">本页由主仓库的 <code>releases.toml</code> 自动生成，请勿直接修改。</p>
</article>
<aside class="toc"><strong>版本</strong>{toc}</aside>
</main>
<footer class="site-footer"><div class="inner"><p>当前版本 {latest.version}</p><p><a href="https://github.com/kder/PyProxySwitch/commits/master/">完整提交历史</a></p></div></footer>
</body></html>
"""


def render_site_news(releases: tuple[Release, ...]) -> str:
    sections = []
    for release in releases[:3]:
        sections.append(
            f'  <section class="release"><h2>PyProxySwitch {release.version}</h2>'
            f"{_time_html(release)}<p>{html.escape(release.summary_zh)}</p>"
            f'<p><a href="changelog.html#{release.anchor}">查看详细变更</a></p></section>'
        )
    return f"""<!doctype html>
<html lang="zh-CN">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="PyProxySwitch 项目动态和版本发布。"><title>项目动态 — PyProxySwitch</title><link rel="stylesheet" href="css/style.css"></head>
<body>
<header class="site-header"><nav class="nav" aria-label="主导航"><a class="brand" href="index.html"><img src="images/PyProxySwitch-Logo.png" alt=""><span>PyProxySwitch</span></a><div class="nav-links"><a href="index.html">首页</a><a href="download.html">下载</a><a href="documentation.html">文档</a><a href="changelog.html">更新记录</a><a href="screenshot.html">界面</a><a href="support.html">支持</a></div></nav><div class="hero compact"><h1>项目动态</h1><p>版本发布和主要用户可见变化。</p></div></header>
<main class="page layout"><article class="content">
{chr(10).join(sections)}
  <p class="muted">更早的版本信息请查阅完整更新记录。</p>
</article><aside class="toc"><strong>相关链接</strong><a href="changelog.html">更新记录</a><a href="https://github.com/kder/PyProxySwitch/commits/master/">提交历史</a><a href="https://github.com/kder/PyProxySwitch/releases">版本发布</a></aside></main>
<footer class="site-footer"><div class="inner"><p>PyProxySwitch 项目动态</p><p><a href="download.html">获取最新版本</a></p></div></footer>
</body></html>
"""


def _replace_once(content: str, pattern: str, replacement: str, relative_path: str) -> str:
    updated, count = re.subn(pattern, replacement, content, count=1)
    if count != 1:
        raise ValueError(f"{relative_path}: expected one match for {pattern!r}, found {count}")
    return updated


def update_site_current_values(site_root: Path, releases: tuple[Release, ...]) -> dict[Path, str]:
    latest = releases[0]
    assert latest.date is not None
    version = latest.version
    release_date = latest.date.isoformat()
    outputs: dict[Path, str] = {}

    rules: dict[str, tuple[tuple[str, str], ...]] = {
        "index.html": (
            (
                rf'<span class="badge"(?: data-release="current")?>当前版本 {VERSION_PATTERN} · \d{{4}}-\d{{2}}-\d{{2}}</span>',
                f'<span class="badge" data-release="current">当前版本 {version} · {release_date}</span>',
            ),
        ),
        "download.html": (
            (
                rf'<meta name="description" content="获取和安装 PyProxySwitch {VERSION_PATTERN}。">',
                f'<meta name="description" content="获取和安装 PyProxySwitch {version}。">',
            ),
            (
                rf'<span class="badge"(?: data-release="current")?>最新版本 {VERSION_PATTERN}</span>',
                f'<span class="badge" data-release="current">最新版本 {version}</span>',
            ),
            (
                rf"# 预期输出：PyProxySwitch {VERSION_PATTERN}",
                f"# 预期输出：PyProxySwitch {version}",
            ),
            (
                rf"新部署请使用 {VERSION_PATTERN} 或更高版本",
                f"新部署请使用 {version} 或更高版本",
            ),
        ),
        "documentation.html": (
            (
                rf'<meta name="description" content="PyProxySwitch {VERSION_PATTERN} 使用、配置和系统要求文档。">',
                f'<meta name="description" content="PyProxySwitch {version} 使用、配置和系统要求文档。">',
            ),
            (
                rf"适用于 PyProxySwitch {VERSION_PATTERN}。",
                f"适用于 PyProxySwitch {version}。",
            ),
            (
                rf"文档对应版本 {VERSION_PATTERN}",
                f"文档对应版本 {version}",
            ),
        ),
        "documentation/system-requirement.html": (
            (
                rf'<meta name="description" content="PyProxySwitch {VERSION_PATTERN} 系统要求、平台支持和协议限制。">',
                f'<meta name="description" content="PyProxySwitch {version} 系统要求、平台支持和协议限制。">',
            ),
        ),
        "sitemap.html": (
            (
                r"站点内容更新于 \d{4}-\d{2}-\d{2}",
                f"站点内容更新于 {release_date}",
            ),
        ),
    }

    for relative_path, replacements in rules.items():
        path = site_root / relative_path
        content = path.read_text(encoding="utf-8")
        for pattern, replacement in replacements:
            content = _replace_once(content, pattern, replacement, relative_path)
        outputs[path] = content
    return outputs


def build_outputs(
    data_file: Path, site_root: Path, expected_version: str | None
) -> tuple[tuple[Release, ...], dict[Path, str]]:
    releases = load_releases(data_file)
    validate_expected_version(releases, expected_version)
    if not site_root.is_dir():
        raise ValueError(
            f"website checkout not found: {site_root}; initialize the htdocs submodule first"
        )

    outputs = {
        REPO_ROOT / "CHANGELOG.md": render_changelog(releases),
        site_root / "changelog.html": render_site_changelog(releases),
        site_root / "news.html": render_site_news(releases),
    }
    outputs.update(update_site_current_values(site_root, releases))
    return releases, outputs


def write_outputs(outputs: dict[Path, str]) -> int:
    changed = 0
    for path, expected in outputs.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual == expected:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
        print(f"updated {path.relative_to(REPO_ROOT)}")
        changed += 1
    print(f"Release documentation synchronized; {changed} file(s) updated.")
    return 0


def check_outputs(outputs: dict[Path, str]) -> int:
    stale = 0
    for path, expected in outputs.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        stale += 1
        print(f"{path.relative_to(REPO_ROOT)} is not synchronized", file=sys.stderr)
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile=f"{path} (generated)",
            lineterm="",
        )
        for line in diff:
            print(line, file=sys.stderr)
    if stale:
        print(
            f"{stale} generated file(s) are stale; run sync_release_docs.py --write",
            file=sys.stderr,
        )
        return 1
    print("Release documentation is synchronized.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated documentation")
    mode.add_argument("--check", action="store_true", help="fail when generated files are stale")
    parser.add_argument(
        "--expected-version",
        help="require the latest release entry to match this version or v-prefixed tag",
    )
    parser.add_argument("--data-file", type=Path, default=DEFAULT_DATA_FILE)
    parser.add_argument("--site-root", type=Path, default=DEFAULT_SITE_ROOT)
    args = parser.parse_args()

    try:
        releases, outputs = build_outputs(
            args.data_file.resolve(),
            args.site_root.resolve(),
            args.expected_version,
        )
    except (OSError, ValueError, tomllib.TOMLDecodeError) as exc:
        parser.error(str(exc))

    latest = releases[0]
    print(f"latest release: {latest.version} ({latest.date.isoformat()})")
    return write_outputs(outputs) if args.write else check_outputs(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
